; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu]
platform = https://github.com/freedib/platform-espressif8266
board = nodemcuv2
framework = esp8266-rtos-sdk

monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp8266_exception_decoder, direct


; how to install this toolchain
; 1) download the xtensa toolchain from https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/windows-setup.html
; 	version 8.4.0 and extract it to .platformio/packages/toolchain-xtensa@8.4.0
; 2) add package.json and .piopm files (copy from another package)
;	.piopm:  {"type": "tool", "name": "toolchain-xtensa", "version": "8.4.0", "spec": {"owner": "platformio", "id": 8221, "name": "toolchain-xtensa", "requirements": null, "uri": null}}
; 
; package.json, line 2: "version": "8.4.0",
; 3) clone from github (recursive) https://github.com/freedib/framework-esp8266-rtos-sdk and change the folder name to include @3.4.0
; 4) copy a .piopm file from another package and change the version to 3.4
; 5) download also https://github.com/freedib/tool-genbin-esp8266
; 6) add .piopm file
;	{"type": "tool", "name": "tool-genbin-esp8266", "version": "1.0.0", "spec": {"owner": "platformio", "id": 11005, "name": "tool-genbin-esp8266", "requirements": null, "uri": null}	
; 7) download mbedtls from the esp8266-rtos-sdk repository and copy the mbedtls folder to .platformio/packages/framework-esp8266-rtos-sdk%403.4/components/mbedtls

